[profile.release]
strip = true
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1

[workspace]
members = [
  "src",
]

[patch.crates-io]
unicode-width = { git = "https://github.com/waltarix/unicode-width", tag = "v0.1.10-custom" }
